from app.controller.repo import RepoClaimAuthHandler
from app.controller.repo_security import RepoSecurityUpdateHandler
from app.controller.auth import AuthHandler
from app.controller.files import FilesHandler
from app.controller.files import ChunkUploadHandler
from app.controller.files import CommitUploadHandler
from app.controller.account_info import AccountInfoHandler
from app.controller.account_info import AccountSecurityQuestionHandler
from app.controller.cursor import CursorHandler
from app.controller.delta import DeltaHandler
from app.controller.metadata import ListFolderHandler
from app.controller.thumbnail import ThumbnailHandler
from app.controller.favorite import FavoriteHandler
from app.controller.filecopymove import FileCopyHandler
from app.controller.filecopymove import FileMoveHandler
from app.controller.filedelete import FileDeleteHandler
from app.controller.filecreatefolder import FileCreateFolderHandler
from app.controller.websocket import WebSocketHandler
from app.controller.version import VersionHandler

